-- begin ZXC_EMPLOYEE
alter table ZXC_EMPLOYEE add constraint FK_ZXC_EMPLOYEE_ON_CUBA_USER_ID foreign key (CUBA_USER_ID_ID) references SEC_USER(ID)^
alter table ZXC_EMPLOYEE add constraint FK_ZXC_EMPLOYEE_ON_CHIEF foreign key (CHIEF_ID) references ZXC_EMPLOYEE(ID)^
alter table ZXC_EMPLOYEE add constraint FK_ZXC_EMPLOYEE_ON_USER_ROLE foreign key (USER_ROLE_ID) references ZXC_USER_ROLE(ID)^
alter table ZXC_EMPLOYEE add constraint FK_ZXC_EMPLOYEE_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references ZXC_DEPARTMENT(ID)^
alter table ZXC_EMPLOYEE add constraint FK_ZXC_EMPLOYEE_ON_TEAM_LEAD foreign key (TEAM_LEAD_ID) references ZXC_EMPLOYEE(ID)^
alter table ZXC_EMPLOYEE add constraint FK_ZXC_EMPLOYEE_ON_POSITION foreign key (POSITION_ID) references ZXC_POSITION(ID)^
create index IDX_ZXC_EMPLOYEE_ON_CUBA_USER_ID on ZXC_EMPLOYEE (CUBA_USER_ID_ID)^
create index IDX_ZXC_EMPLOYEE_ON_CHIEF on ZXC_EMPLOYEE (CHIEF_ID)^
create index IDX_ZXC_EMPLOYEE_ON_USER_ROLE on ZXC_EMPLOYEE (USER_ROLE_ID)^
create index IDX_ZXC_EMPLOYEE_ON_DEPARTMENT on ZXC_EMPLOYEE (DEPARTMENT_ID)^
create index IDX_ZXC_EMPLOYEE_ON_TEAM_LEAD on ZXC_EMPLOYEE (TEAM_LEAD_ID)^
create index IDX_ZXC_EMPLOYEE_ON_POSITION on ZXC_EMPLOYEE (POSITION_ID)^
create index IDX_ZXC_EMPLOYEE on ZXC_EMPLOYEE (FIO) ^
-- end ZXC_EMPLOYEE

-- begin ZXC_INDIVIDUAL_CAREER_PLAN
alter table ZXC_INDIVIDUAL_CAREER_PLAN add constraint FK_ZXC_INDIVIDUAL_CAREER_PLAN_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ZXC_EMPLOYEE(ID)^
alter table ZXC_INDIVIDUAL_CAREER_PLAN add constraint FK_ZXC_INDIVIDUAL_CAREER_PLAN_ON_GRADE foreign key (GRADE_ID) references ZXC_GRADE(ID)^
create index IDX_ZXC_INDIVIDUAL_CAREER_PLAN_ON_EMPLOYEE on ZXC_INDIVIDUAL_CAREER_PLAN (EMPLOYEE_ID)^
create index IDX_ZXC_INDIVIDUAL_CAREER_PLAN_ON_GRADE on ZXC_INDIVIDUAL_CAREER_PLAN (GRADE_ID)^
-- end ZXC_INDIVIDUAL_CAREER_PLAN
-- begin ZXC_COMPETENCY
alter table ZXC_COMPETENCY add constraint FK_ZXC_COMPETENCY_ON_EMPLOYEE_MASTER foreign key (EMPLOYEE_MASTER_ID) references ZXC_EMPLOYEE(ID)^
create unique index IDX_ZXC_COMPETENCY_UNIQ_NAME on ZXC_COMPETENCY (NAME) ^
create index IDX_ZXC_COMPETENCY_ON_EMPLOYEE_MASTER on ZXC_COMPETENCY (EMPLOYEE_MASTER_ID)^
-- end ZXC_COMPETENCY

-- begin ZXC_IPRDETAIL
alter table ZXC_IPRDETAIL add constraint FK_ZXC_IPRDETAIL_ON_COMPETENCY foreign key (COMPETENCY_ID) references ZXC_COMPETENCY(ID)^
alter table ZXC_IPRDETAIL add constraint FK_ZXC_IPRDETAIL_ON_GRADE foreign key (GRADE_ID) references ZXC_GRADE(ID)^
alter table ZXC_IPRDETAIL add constraint FK_ZXC_IPRDETAIL_ON_INDIVIDUAL_CAREER_PLAN foreign key (INDIVIDUAL_CAREER_PLAN_ID) references ZXC_INDIVIDUAL_CAREER_PLAN(ID)^
create index IDX_ZXC_IPRDETAIL_ON_COMPETENCY on ZXC_IPRDETAIL (COMPETENCY_ID)^
create index IDX_ZXC_IPRDETAIL_ON_GRADE on ZXC_IPRDETAIL (GRADE_ID)^
create index IDX_ZXC_IPRDETAIL_ON_INDIVIDUAL_CAREER_PLAN on ZXC_IPRDETAIL (INDIVIDUAL_CAREER_PLAN_ID)^
-- end ZXC_IPRDETAIL

-- begin ZXC_WORK_PLAN
alter table ZXC_WORK_PLAN add constraint FK_ZXC_WORK_PLAN_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ZXC_EMPLOYEE(ID)^
alter table ZXC_WORK_PLAN add constraint FK_ZXC_WORK_PLAN_ON_GRADE foreign key (GRADE_ID) references ZXC_GRADE(ID)^
alter table ZXC_WORK_PLAN add constraint FK_ZXC_WORK_PLAN_ON_MY_GRADE foreign key (MY_GRADE_ID) references ZXC_GRADE(ID)^
alter table ZXC_WORK_PLAN add constraint FK_ZXC_WORK_PLAN_ON_PLAN_QUARTER foreign key (PLAN_QUARTER_ID) references ZXC_QUARTERS_DICT(ID)^
create unique index IDX_ZXC_WORK_PLAN_UNQ on ZXC_WORK_PLAN (EMPLOYEE_ID) ^
create index IDX_ZXC_WORK_PLAN_ON_EMPLOYEE on ZXC_WORK_PLAN (EMPLOYEE_ID)^
create index IDX_ZXC_WORK_PLAN_ON_GRADE on ZXC_WORK_PLAN (GRADE_ID)^
create index IDX_ZXC_WORK_PLAN_ON_MY_GRADE on ZXC_WORK_PLAN (MY_GRADE_ID)^
create index IDX_ZXC_WORK_PLAN_ON_PLAN_QUARTER on ZXC_WORK_PLAN (PLAN_QUARTER_ID)^
-- end ZXC_WORK_PLAN

-- begin ZXC_WORK_PLAN_DETAIL
alter table ZXC_WORK_PLAN_DETAIL add constraint FK_ZXC_WORK_PLAN_DETAIL_ON_WORK_PLAN foreign key (WORK_PLAN_ID) references ZXC_WORK_PLAN(ID)^
alter table ZXC_WORK_PLAN_DETAIL add constraint FK_ZXC_WORK_PLAN_DETAIL_ON_PROJECT foreign key (PROJECT_ID) references ZXC_PROJECT(ID)^
alter table ZXC_WORK_PLAN_DETAIL add constraint FK_ZXC_WORK_PLAN_DETAIL_ON_GRADE foreign key (GRADE_ID) references ZXC_GRADE(ID)^
create index IDX_ZXC_WORK_PLAN_DETAIL_ON_WORK_PLAN on ZXC_WORK_PLAN_DETAIL (WORK_PLAN_ID)^
create index IDX_ZXC_WORK_PLAN_DETAIL_ON_PROJECT on ZXC_WORK_PLAN_DETAIL (PROJECT_ID)^
create index IDX_ZXC_WORK_PLAN_DETAIL_ON_GRADE on ZXC_WORK_PLAN_DETAIL (GRADE_ID)^
-- end ZXC_WORK_PLAN_DETAIL
-- begin ZXC_WORK_PLAN_DETAIL_TASK
alter table ZXC_WORK_PLAN_DETAIL_TASK add constraint FK_ZXC_WORK_PLAN_DETAIL_TASK_ON_WORK_PLAN foreign key (WORK_PLAN_ID) references ZXC_WORK_PLAN(ID)^
alter table ZXC_WORK_PLAN_DETAIL_TASK add constraint FK_ZXC_WORK_PLAN_DETAIL_TASK_ON_RESULT_GRADE foreign key (RESULT_GRADE_ID) references ZXC_GRADE(ID)^
create index IDX_ZXC_WORK_PLAN_DETAIL_TASK_ON_WORK_PLAN on ZXC_WORK_PLAN_DETAIL_TASK (WORK_PLAN_ID)^
create index IDX_ZXC_WORK_PLAN_DETAIL_TASK_ON_RESULT_GRADE on ZXC_WORK_PLAN_DETAIL_TASK (RESULT_GRADE_ID)^
-- end ZXC_WORK_PLAN_DETAIL_TASK
-- begin ZXC_FEEDBACK
alter table ZXC_FEEDBACK add constraint FK_ZXC_FEEDBACK_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ZXC_EMPLOYEE(ID)^
create index IDX_ZXC_FEEDBACK_ON_EMPLOYEE on ZXC_FEEDBACK (EMPLOYEE_ID)^
-- end ZXC_FEEDBACK
-- begin ZXC_EMPLOYEE_PROFILE
alter table ZXC_EMPLOYEE_PROFILE add constraint FK_ZXC_EMPLOYEE_PROFILE_AVATAR foreign key (AVATAR_ID) references SYS_FILE(ID)^
-- end ZXC_EMPLOYEE_PROFILE
