alter table ZXC_INDIVIDUAL_CAREER_PLAN add constraint FK_ZXC_INDIVIDUAL_CAREER_PLAN_ON_GRADE foreign key (GRADE_ID) references ZXC_GRADE(ID);
create index IDX_ZXC_INDIVIDUAL_CAREER_PLAN_ON_GRADE on ZXC_INDIVIDUAL_CAREER_PLAN (GRADE_ID);
