alter table ZXC_IPRCOMPETENCY add constraint FK_ZXC_IPRCOMPETENCY_ON_IPR foreign key (IPR_ID) references ZXC_INDIVIDUAL_CAREER_PLAN(ID);
create index IDX_ZXC_IPRCOMPETENCY_ON_IPR on ZXC_IPRCOMPETENCY (IPR_ID);
