alter table ZXC_INDIVIDUAL_CAREER_PLAN add constraint FK_ZXC_INDIVIDUAL_CAREER_PLAN_ON_IPRCOMP foreign key (IPRCOMP_ID) references ZXC_IPRCOMP(ID);
create index IDX_ZXC_INDIVIDUAL_CAREER_PLAN_ON_IPRCOMP on ZXC_INDIVIDUAL_CAREER_PLAN (IPRCOMP_ID);
