alter table ZXC_COMPETENCY add constraint FK_ZXC_COMPETENCY_ON_EMPLOYEE_MASTER foreign key (EMPLOYEE_MASTER_ID) references ZXC_EMPLOYEE(ID);
create index IDX_ZXC_COMPETENCY_ON_EMPLOYEE_MASTER on ZXC_COMPETENCY (EMPLOYEE_MASTER_ID);
