alter table ZXC_IPRDETAIL add constraint FK_ZXC_IPRDETAIL_ON_COMPETENCY foreign key (COMPETENCY_ID) references ZXC_COMPETENCY(ID);
create index IDX_ZXC_IPRDETAIL_ON_COMPETENCY on ZXC_IPRDETAIL (COMPETENCY_ID);
