alter table ZXC_EMPLOYEE add constraint FK_ZXC_EMPLOYEE_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references ZXC_DEPARTMENT(ID);
create index IDX_ZXC_EMPLOYEE_ON_DEPARTMENT on ZXC_EMPLOYEE (DEPARTMENT_ID);
