alter table ZXC_WORK_PLAN_DETAIL add constraint FK_ZXC_WORK_PLAN_DETAIL_ON_PROJECT foreign key (PROJECT_ID) references ZXC_PROJECT(ID);
create index IDX_ZXC_WORK_PLAN_DETAIL_ON_PROJECT on ZXC_WORK_PLAN_DETAIL (PROJECT_ID);
