alter table ZXC_WORK_PLAN_DETAIL add constraint FK_ZXC_WORK_PLAN_DETAIL_ON_WORK_PLAN foreign key (WORK_PLAN_ID) references ZXC_WORK_PLAN(ID);
create index IDX_ZXC_WORK_PLAN_DETAIL_ON_WORK_PLAN on ZXC_WORK_PLAN_DETAIL (WORK_PLAN_ID);
