alter table ZXC_WORK_PLAN_DETAIL add constraint FK_ZXC_WORK_PLAN_DETAIL_ON_PROJECTS foreign key (PROJECTS_ID) references ZXC_PROJECT(ID);
create index IDX_ZXC_WORK_PLAN_DETAIL_ON_PROJECTS on ZXC_WORK_PLAN_DETAIL (PROJECTS_ID);
