alter table ZXC_WORK_PLAN add constraint FK_ZXC_WORK_PLAN_ON_PLAN_QUARTER foreign key (PLAN_QUARTER_ID) references ZXC_QUARTERS_DICT(ID);
create index IDX_ZXC_WORK_PLAN_ON_PLAN_QUARTER on ZXC_WORK_PLAN (PLAN_QUARTER_ID);
